version: "3.5"
services:
    spider:
        build: .
        restart: always
        networks: 
            mooc_net:
                aliases:
                    - spider
        ports:
            - "8095:8081"
    web:
        build: frontend/
        ports:
            - "5000:80"
        networks: 
            - mooc_net
        depends_on:
            - spider
            
networks:
    mooc_net:
